service: serverless-aws-lambda

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/handler.hello

    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    src